name: stable-diffusion-cpu

dependencies:
  - python=3.9
  - notebook
  - scipy
  - transformers
  - diffusers
  - ftfy
  - ipywidgets
  - panel

channels:
  - defaults
  - conda-forge

platforms:
  - osx-arm64
  - osx-64
  - linux-64
  - win-64
